Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "linux-containers-lab"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.network "private_network", type: "dhcp"

  config.vm.provision "shell", inline: <<-SHELL
    set -e

    # Mettre à jour les paquets
    apt-get update
    apt-get upgrade -y

    # Installer les outils nécessaires
    apt-get install -y \
      util-linux \
      cgroup-tools \
      debootstrap \
      curl \
      wget \
      gnupg2 \
      net-tools \
      lsof \
      iproute2

    # Créer dossier de travail pour les TP
    mkdir -p /home/vagrant/tp-containers/rootfs
    chown -R vagrant:vagrant /home/vagrant/tp-containers

    # Installer crictl (optionnel)
    VERSION="v1.28.0"
    curl -LO https://github.com/kubernetes-sigs/cri-tools/releases/download/${VERSION}/crictl-${VERSION}-linux-amd64.tar.gz
    tar -C /usr/local/bin -zxvf crictl-${VERSION}-linux-amd64.tar.gz
    rm crictl-${VERSION}-linux-amd64.tar.gz

    # Clean
    apt-get clean
  SHELL
end
