Vagrant.configure("2") do |config|
  # Box Ubuntu 22.04 LTS (Jammy)
  config.vm.box = "ubuntu/jammy64"

  # Configuration de la VM
  config.vm.hostname = "minikube-lab"
  config.vm.network "private_network", ip: "192.168.56.50"
  # Forcer SSH avec la clé "insecure_private_key"
  config.ssh.insert_key = false
  config.ssh.username = "vagrant"
  config.ssh.private_key_path = ["#{ENV['USERPROFILE']}/.vagrant.d/insecure_private_key"]
  config.vm.provider "virtualbox" do |vb|
    vb.name = "minikube-lab"
    vb.memory = "8192"   # 8 Go RAM
    vb.cpus = 2
  end

  # Provisionnement
  config.vm.provision "shell", inline: <<-SHELL
    # Mise à jour système
    apt-get update -y && apt-get upgrade -y

    # Installation dépendances
    apt-get install -y apt-transport-https ca-certificates curl software-properties-common conntrack

    # Installation Docker
    curl -fsSL https://get.docker.com | sh
    usermod -aG docker vagrant

    # Installation kubectl
   curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

kubectl version --client


    # Installation Minikube
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    install minikube-linux-amd64 /usr/local/bin/minikube
    rm minikube-linux-amd64

    # Installation Helm
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    # Démarrage automatique de Minikube (driver Docker)
    sudo -u vagrant minikube start --driver=docker --memory=6000mb --cpus=2
    sudo apt install maven
    sudo apt install -y openjdk-17-jdk openjdk-17-jre
  SHELL
end
